import type { Metadata } from "next";
import { Noto_Sans_Mono as FontSans } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import NavBar from "../components/navbar";

import { cn } from "../lib/utils";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import  ThemeProvider  from "./theme-provider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const inter = FontSans({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Jeremy Sebring",
  description: "Generated by Jeremy, GPT, and Stack Overflow",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header className="container mx-auto pb-3">
          <NavBar />
        </header>

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <main>
            {children}
            <Analytics />
            <SpeedInsights />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
